services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "10"
    ports:
      - 22181:2181
    networks:
      - finnekta-core

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    depends_on:
      - zookeeper
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "10"
    ports:
      - 29092:29092
      - 9092:9092
      - 9093:9093
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      # KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      # KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      # KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092,PLAINTEXT_EXTERNAL://192.168.16.21:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,PLAINTEXT_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1  # Configuración para transacciones
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1             # Configuración para transacciones
    networks:
      - finnekta-core
    healthcheck:
      test: [ "CMD", "kafka-topics", "--zookeeper", "zookeeper:2181", "--list" ]
      interval: 10s
      timeout: 10s
      retries: 10

  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "10"
    ports:
      - "9411:9411"
    networks:
      - finnekta-core

  redpanda:
    image: docker.redpanda.com/redpandadata/console:v2.6.0
    container_name: redpanda
    depends_on:
      - kafka
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "10"
    ports:
      - "8080:8080"
    environment:
      KAFKA_BROKERS: kafka:9092
      SERVER_PORT: 8080
    networks:
      - finnekta-core

networks:
  finnekta-core:
    name: finnekta-core
